[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cherry-files-toolkit"
version = "0.1.2"
description = "TUI toolkit for cherry-picking files between git branches"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = ["textual"]
authors = [{ name = "Nelson Urrutia", email = "nelurrutia15@gmail.com" }]

[project.urls]
Repository = "https://github.com/NelsonUrrutia/cherry-files-toolkit"

[project.scripts]
cherry-files-toolkit = "cherry_files_toolkit.main:run"

[tool.hatch.build.targets.sdist]
include = ["/cherry_files_toolkit", "/LICENSE", "/README.md", "/pyproject.toml"]

[tool.hatch.build.targets.wheel]
packages = ["cherry_files_toolkit"]
